### ISSUE TITLE
Problem running code

### ISSUE THREAD

**Issue by Sweezy777** [3b1b/videos#39]
I use Kali Linux as my OS and whenever I try and run simulations.py I get:
┌──(root💀lookaway)-[/home/***/wordle/_2022/wordle]
└─# python3 simulations.py                      
zsh: segmentation fault  python3 simulations.py

I dont even understand what to run? should I run simulations? or scenes? or quinitic?

In my folder I have:
/home/***/wordle/_2022/wordle/custom
/home/***/wordle/_2022/wordle/data
/home/***/wordle/_2022/wordle/__pycache__
/home/***/wordle/_2022/wordle/footnote.py
/home/***/wordle/_2022/wordle/manim_imports_ext.py
/home/***/wordle/_2022/wordle/scenes.py
/home/***/wordle/_2022/wordle/simulations.py

**Comment by Sweezy777** [comment]
https://github.com/3b1b/manim#installation
i found that, i dont know what it means... brb

**Comment by Sweezy777** [comment]
**oh rip... I installed that ^^^ and now I get an even longer error code:**
┌──(***㉿lookaway)-[~/wordle/_2022/wordle]
└─$ python3.9 ./simulations.py                                                                                                                                                      2 ⨯
/home/***/.local/lib/python3.9/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "/home/***/wordle/_2022/wordle/./simulations.py", line 1, in <module>
    from manim_imports_ext import *
  File "/home/***/wordle/_2022/wordle/manim_imports_ext.py", line 3, in <module>
    from custom.backdrops import *
  File "/home/***/wordle/_2022/wordle/custom/backdrops.py", line 10, in <module>
    from manimlib.mobject.svg.tex_mobject import TexText
ImportError: cannot import name 'TexText' from 'manimlib.mobject.svg.tex_mobject' (/home/***/.local/lib/python3.9/site-packages/manimlib/mobject/svg/tex_mobject.py)

**Comment by cornflakesdev** [comment]
Similar issue resolved https://github.com/3b1b/videos/issues/41
