### ISSUE TITLE
MovingCameraScene

### ISSUE THREAD

**Issue by Volker-Weissmann** [3b1b/videos#6]
Hello,
some older cases don't work anymore, since MovingCameraScene was removed:

Example:
```
$ python _2019/diffyq/all_part1_scenes.py 
Traceback (most recent call last):
  File "/home/volker/cloned/videos/_2019/diffyq/all_part1_scenes.py", line 1, in <module>
    from _2019.diffyq.part1.pendulum import *
  File "/home/volker/cloned/videos/_2019/diffyq/part1/pendulum.py", line 357, in <module>
    class IntroducePendulum(PiCreatureScene, MovingCameraScene):
NameError: name 'MovingCameraScene' is not defined
```

```
[volker@battle 3b1b]$ rg MovingCamera
docs/source/getting_started/whatsnew.rst:29:  - Removed all camera classes except ``Camera`` (``MappingCamera``, ``MovingCamera``, ``MultiCamera``) and all functions in ``ThreeDCamera``
docs/source/getting_started/whatsnew.rst:123:  - Removed all functions of ``GraphScene`` (moved to ``once_useful_constructs``), ``MovingCameraScene``, ``ReconfigurableScene``, ``SceneFromVideo``, ``ZoomedScene``, and ``ThreeDScene``. Because these can basically be achieved by adjusting ``CameraFrame`` (``self.camera.frame``)  
```

**Comment by jincy-p-janardhanan** [comment]
As mentioned in the [Manim Community Documentation](https://docs.manim.community/en/stable/installation/versions.html#which-version-to-use),

> If you would like to render old 3Blue1Brown projects (2019 and before), you should use ManimCairo.

Also, 
> ManimCairo: The old version of manim originally used by 3blue1brown. It is not available on pip. 

So you should be using the ManimCairo version which can be downloaded from [here](https://github.com/3b1b/manim/tree/cairo-backend).
