### ISSUE TITLE
cant install 'custom'

### ISSUE THREAD

**Issue by Caterpillar-Conlin** [3b1b/videos#67]
![Uploading image.png…]()

**Comment by Caterpillar-Conlin** [comment]
(base) PS C:\Users\conlin24\Desktop\work\videos-master> pip install custom          
Defaulting to user installation because normal site-packages is not writeable
Collecting custom
  Using cached custom-0.1.1.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\conlin24\AppData\Local\Temp\pip-install-8o1l2pfl\custom_6f63dc1271884fa0825bd07e898bc411\setup.py", line 12, in <module>
          from custom.CustomCarry import __version__
        File "C:\Users\conlin24\AppData\Local\Temp\pip-install-8o1l2pfl\custom_6f63dc1271884fa0825bd07e898bc411\custom\CustomCarry\__init__.py", line 3, in <modu
le>
          from custom import CustomCarry, change_custom_seed
      ImportError: cannot import name 'change_custom_seed' from 'custom' (C:\Users\conlin24\AppData\Local\Temp\pip-install-8o1l2pfl\custom_6f63dc1271884fa0825bd0
7e898bc411\custom\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
